const Router = require('express')
const router = new Router()
const directionRouter = require('./directionRouter')
const project_stackRouter = require('./project_stackRouter')
const project_userRouter = require('./project_userRouter')
const projectRouter = require('./projectRouter')
const refresh_tokenRouter = require('./refresh_tokenRouter')
const stackRouter = require('./stackRouter')
const user_learn_historyRouter = require('./user_learn_historyRouter')
const user_learnRouter = require('./user_learnRouter')
const user_personalRouter = require('./user_personalRouter')
const user_stackRouter = require('./user_stackRouter')
const userRouter = require('./userRouter')

router.use('/direction', directionRouter)
router.use('/project_stack', project_stackRouter)
router.use('/project_user', project_userRouter)
router.use('/project', projectRouter)
router.use('/refresh_token', refresh_tokenRouter)
router.use('/stack', stackRouter)
router.use('/user_learn_history', user_learn_historyRouter)
router.use('/user_learn', user_learnRouter)
router.use('/user_personal', user_personalRouter)
router.use('/user_stack', user_stackRouter)
router.use('/user', userRouter)

module.exports = router 